import localFont from "next/font/local";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  weight: "100 900",
  style: "normal",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const tabs = [
  {
    title: "검색",
    iconUrl: "/images/icons/pageview.png",
    href: "/",
  },
  {
    title: "내 카드",
    iconUrl: "/images/icons/add_card.png",
    href: "/",
  },
  {
    title: "혜택 지도",
    iconUrl: "/images/icons/pin_drop.png",
    href: "/",
  },
  {
    title: "카드 추천",
    iconUrl: "/images/icons/credit_card.png",
    href: "/",
  },
  {
    title: "더보기",
    iconUrl: "/images/icons/menu.png",
    href: "/",
  },
]

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body className={pretendard.className}>
        <div className="h-screen relative">
          {children}
          <div className="absolute z-50 bottom-0 w-full h-20 pt-2.5 px-[25px] bg-white" style={{ boxShadow: '0px 4px 10px 0px rgba(0, 0, 0, 0.08)' }}>
            <div className="flex items-center space-x-[30px]">
              {tabs.map((tab) => (
                <Link key={tab.title} href={tab.href} className="w-[41px] h-[41px] flex flex-col items-center space-y-0.5">
                  <Image src={tab.iconUrl} width={24} height={24} alt={tab.title} />
                  <div className="text-[#6D727A] text-[11px]">{tab.title}</div>
                </Link>
              ))}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
